version: '3.1'

services:
  api:
    build:
      context: ./
      dockerfile: ./Api/Dockerfile
    container_name: pii-api.service
    restart: always
    ports:
      - 8888:80
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      backend:
        aliases:
          - api

  migration:
    build:
      context: ./
      dockerfile: ./Migration/Dockerfile
    container_name: pii-migration.service
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      backend:
        aliases:
          - migration

  mysql:
    image: mysql
    container_name: pii-mysql.service
    restart: always
    environment:
      MYSQL_DATABASE: pii
      MYSQL_ROOT_PASSWORD: root
    networks:
      backend:
        aliases:
          - database

networks:
  backend:
    name: network
