version: '3.1'

services:
  api:
    build:
      context: ./
      dockerfile: ./Api/Dockerfile
    container_name: api.service
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      backend:
        aliases:
          - webapi

  mysql:
    image: mysql
    container_name: mysql.db
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: pii
      MYSQL_ROOT_PASSWORD: root
  
  mongo:
    image: mongo
    restart: always
    container_name: mongo.service
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      backend:
        aliases:
          - mongo.service

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - mongo-express.service

networks:
  backend:
    name: network
