version: '3.1'

services:
  api:
    build:
      context: ./
      dockerfile: ./Api/Dockerfile
    container_name: api.service
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      backend:
        aliases:
          - webapi

  mysql:
    image: mysql
    container_name: mysql.db
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: pii
      MYSQL_ROOT_PASSWORD: root

networks:
  backend:
    name: network
